version: "3.6"

services:
    flask: 
        build: ./
        container_name: flask
        restart: always
        environment:
            - APP_NAME=chungoba
        expose: - 8080
        
    nginx: 
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "5000:5000