version: 2
jobs:
  tests:
    docker:
      - image: circleci/python:3.6.6

    working_directory: ~/chungoba

    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
          - deps-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . env/bin/activate
            python manager.py test
      - save_cache:
          paths:
            - ./env
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}