# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: [ubuntu-latest]
    env:
      working-directory: ./
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install virtualenv
        virtualenv env
        . env/bin/activate
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      working-directory: ${{ env.working-directory }}

    - name: test.sh
      run: |
        ls
        git config user.name zio
        git config user.email zio4272@naver.com
        git config github.token ${{ secrets.GITHUB_TOKEN }}
        git add .
        git commit -a "generated"
        git push
        git config pull.rebase false
        git pull origin master
      working-directory: ${{ env.working-directory }}